version: '3.4'

services:
  client:
    image: photo-gallery-asgmnt
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - photo-gallery-app
  api:
    image: photo-gallery-backend
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    networks:
      - photo-gallery-app
    depends_on:
      - mongodb
  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      networks:
      - photo-gallery-app
  networks:
    photo-gallery-app:
      driver: bridge
